-- ============================================================
-- 02_load/03_narrative.sql
-- PURPOSE : fill complaint_narrative — only rows that have text
-- SOURCE  : stg_complaints_raw  ->  modelled tables
-- ============================================================
-- STEPS
--  1. From window rows in staging, keep complaint_id + narrative where the narrative is
--     not NULL and not blank.
--  2. INSERT INTO complaint_narrative (complaint_id, narrative). n_words fills itself.  expect 1,639,068
--  3. The foreign key guarantees every narrative has a fact row — if the insert errors, the
--     fact load (02_fact) is incomplete.

-- your query here
