-- ============================================================
-- 02_load/05_validate.sql
-- PURPOSE : row counts after EVERY step; no fact row may lose its dimension (inner-join count = total)
-- SOURCE  : stg_complaints_raw  ->  modelled tables
-- ============================================================
-- STEPS    every one must match before moving on
--  1. Row counts: fact 4,826,564 · narrative 1,639,068 · events 14,479,692
--  2. Grain: count(*) = count(DISTINCT complaint_id) on fact and narrative.
--  3. Every complaint has all 3 events: GROUP BY complaint_id HAVING count(*) <> 3 -> 0 rows.
--  4. Label count: 'responded' events with company_response = 'Closed with monetary relief'
--                                                                                   expect 60,952 (F1)
--  5. Crosswalk worked: count fact rows where raw_product <> canonical product name  expect 1,334,958
--  6. No stray old names: dim_product must NOT contain 'Credit card or prepaid card'.
--  7. Then run 06_indexes.sql.

-- your query here
